# Generated by Django 4.2.9 on 2024-01-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='writer',
            new_name='owner',
        ),
    ]
